apiVersion: tutorial.foo.op/v1
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: foo
    app.kubernetes.io/instance: foo-sample
    app.kubernetes.io/part-of: foo-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: foo-operator
  name: foo-01
spec:
  # TODO(user): Add fields here
  name: jack
